[package]
name = "prockit"
version = "0.1.0"
edition = "2024"

[dependencies]
derive_more = { workspace = true, features = ["constructor", "from"] }
easy-ext.workspace = true
proc-macro2.workspace = true
quote.workspace = true
syn.workspace = true
